### ISSUE TITLE
Handlebars 1.10.1 : RegisterHelper different?

### ISSUE THREAD

**Issue by StefH** [rexm/Handlebars.Net#298] opened 2019-05-03 11:40 UTC
I register this handlebars custom code:
``` c#
handlebarsContext.RegisterHelper("Random", (writer, context, arguments) =>
{
});
```
And when processing this text:
`{{Random Type=\"Text\" Min=8 Max=20}}`

The arguments look like this:
![image](https://user-images.githubusercontent.com/249938/57135224-eb3baa00-6da8-11e9-9cd3-88f51e82b6bb.png)

Note that the **Min** and **Max** are defined as a string instead of a int ?

Is this something which has been changed lately?

**Comment by StefH** [comment] 2019-05-03 11:47
In version 1.9.5 it look like:
![image](https://user-images.githubusercontent.com/249938/57135508-f04d2900-6da9-11e9-8958-fa0979a93fd3.png)

**Comment by rexm** [comment] 2019-05-12 17:12
I dug into this a little and tbh I'm not sure how it was ever an int... still looking into it

**Comment by StefH** [comment] 2019-05-12 17:36
But an **int** in case of `{{Random Min=8}}` does make sense? No?
In case I wanted a string, I would use double-quotes like `{{Random Type=\"Text\"}}`

**Comment by rexm** [comment] 2019-05-12 18:33
It is sensible but will take more work to make it happen

**Comment by StefH** [comment] 2019-05-13 05:29
Could this different behaviour be triggered by this code:
Added support for Raw Blocks / Quad Mustache syntax (#289)  ?

**Comment by vzwick** [comment] 2019-06-03 13:18
I went back through the commits to narrow this one down: 528555640934b12ad5a8ea0d29dba421ca1ebf91 (#262) seems to be the culprit.

**Comment by rexm** [comment] 2019-06-03 14:26
Good find! If you’re in a hurry go ahead and put in a PR (with a few tests so we’ll catch this one) and I’ll merge & publish.

**Comment by vzwick** [comment] 2019-06-03 15:21
@rexm I'm afraid it's not a straightforward fix and I'm somewhat short on time ... Will probably take a look later this week if no one else tackles this.

Btw, how about an "up for grabs" label?

**Comment by rexm** [comment] 2019-06-04 22:58
They are all up for grabs ;)

**Comment by StefH** [comment] 2019-06-06 06:03
My first idea was to change the **LiteralConverter** to parse the arguments as a bool or int as it was done before, like this:
``` c#
public override IEnumerable<object> ConvertTokens(IEnumerable<object> sequence)
{
    foreach (var item in sequence)
    {
        if (item is LiteralExpressionToken literalExpression)
        {
            Expression result;
            if (bool.TryParse(literalExpression.Value, out bool boolValue))
            {
                result = Expression.Constant(boolValue);
            }
            else if (int.TryParse(literalExpression.Value, out int intValue))
            {
                result = Expression.Constant(intValue);
            }
            else
            {
                result = Expression.Constant(literalExpression.Value);
            }

            yield return result;
        }
        else
        {
            yield return item;
        }
    }
}
```
This works fine, however the code throws an exception in **HelperFunctionBinder** at this line:
```  c#
Expression.NewArrayInit(typeof(object), hex.Arguments.Select(a => Visit(a)))
```
Because an Constant Expression of an `int` cannot be cast to an `object`.

And when changing that code to :
``` c#
Expression.NewArrayInit(typeof(object), hex.Arguments.Select(a => Expression.Convert(a, typeof(object))))
```

About 22 tests fail...

**Comment by pmccloghrylaing** [comment] 2019-07-16 23:58
What's the expected behaviour here?

I'm looking at this and it seems to be different between hash parameters and unnamed arguments. I can see that `{{helper min=1}}` should handle `1` as an `int`, but it seems like `{{helper 1}}` should pass `1` as an `int` as well - but based on the tests this seems to be a breaking change.

**Comment by 304NotModified** [comment] 2019-08-06 20:59
I think the expected behavior is an int? Then this is a big which should be fixed and proper unit tested IMO.

**Comment by pmccloghrylaing** [comment] 2019-08-07 23:24
I've opened a PR for this - #319

**Closed** 2019-08-08 10:26 UTC
Labels: help wanted
