### ISSUE TITLE
Handlebars crashes with AccessViolationException for async operations

### ISSUE THREAD

**Issue by EBMike** [rexm/Handlebars.Net#228] opened 2017-10-13 20:21 UTC
clone [this public repo example](https://github.com/EventBooking/HandlebarsTestRepo)

* uses the 1.9.0 nuget package (released on May 16th)
* I should mention this is confusing. **The Nuget is released on May 16th but the release tag for 1.9.0 is May 19th**
* if you clone the Handlebars.Net repo at the hash the nuget package is built and rebuild it with Visual Studio 2017 it works fine. (assuming the 1.9.0 release tag is the same as the nuget package, see point above)

Make sure to run the clone repo with Visual Studio 2017

run the only test in there... it will crash, i promise. the test is set to run 100 operations intentionally to crash every time. you will see the template is minimal. Removing anything in the file will allow it to pass, this is the smallest file I could make that would crash.

```System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.```

* **special note: I clone this repo at v1.9.0 and added the test and it works fine. This seems to only be an issue with the nuget dll**

**Comment by rexm** [comment] 2017-10-19 15:52
I cloned the repo and ran it unmodified in VS 2017, unfortunately cannot reproduce this as you described. There must be another variable.

**Comment by mikeprince3** [comment] 2017-10-24 20:39
For what it's worth, I cloned the repo and encountered the same error that was reported. 

[10/24/2017 4:07:48 PM Informational] ------ Load Playlist started ------
[10/24/2017 4:07:48 PM Informational] ========== Load Playlist finished (0:00:00.0034994) ==========
[10/24/2017 4:08:12 PM Informational] ------ Discover test started ------
[10/24/2017 4:08:14 PM Informational] [xUnit.net 00:00:00.6818483]   Discovering: HandlebarsTests
[10/24/2017 4:08:14 PM Informational] [xUnit.net 00:00:00.7951338]   Discovered:  HandlebarsTests
[10/24/2017 4:08:14 PM Informational] ========== Discover test finished: 1 found (0:00:02.4518913) ==========
[10/24/2017 4:08:17 PM Informational] ------ Run test started ------
[10/24/2017 4:08:18 PM Informational] [xUnit.net 00:00:00.5743527]   Discovering: HandlebarsTests
[10/24/2017 4:08:18 PM Informational] [xUnit.net 00:00:00.6779277]   Discovered:  HandlebarsTests
[10/24/2017 4:08:18 PM Informational] [xUnit.net 00:00:00.7243715]   Starting:    HandlebarsTests
[10/24/2017 4:08:22 PM Error] The active test run was aborted. Reason: onContext, ContextCallback callback, Object state)
System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at System.Runtime.CompilerServices.RuntimeHelpers._CompileMethod(IRuntimeMethodInfo method)
   at System.Reflection.Emit.DynamicMethod.CreateDelegate(Type delegateType, Object target)
   at System.Linq.Expressions.Compiler.LambdaCompiler.CreateDelegate()
   at System.Linq.Expressions.Compiler.LambdaCompiler.Compile(LambdaExpression lambda)
   at System.Linq.Expressions.Expression`1.Compile(Boolean preferInterpretation)
   at HandlebarsDotNet.Compiler.FunctionBuilder.Compile(IEnumerable`1 expressions, String templatePath)
   at HandlebarsDotNet.Handlebars.HandlebarsEnvironment.Compile(String template)
   at HandlebarsTests.Tests.<RunPrecompiled>d__1.MoveNext() in D:\Repositories\git\HandlebarsTestRepo\HandlebarsTests\Tests.cs:line 25
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.RunWithDefaultContext()
   at Xunit.Sdk.AsyncTestSyncContext.<>c__DisplayClass7_0.<Post>b__1(Object _)
   at Xunit.Sdk.MaxConcurrencySyncContext.RunOnSyncContext(SendOrPostCallback callback, Object state)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at Xunit.Sdk.MaxConcurrencySyncContext.WorkerThreadProc()
   at Xunit.Sdk.XunitWorkerThread.<>c.<QueueUserWorkItem>b__5_0(Object _)
   at System.Threading.Tasks.Task.Execute()
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
   at System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at System.Runtime.CompilerServices.RuntimeHelpers._CompileMethod(IRuntimeMethodInfo method)
   at System.Reflection.Emit.DynamicMethod.CreateDelegate(Type delegateType, Object target)
   at System.Linq.Expressions.Compiler.LambdaCompiler.CreateDelegate()
   at System.Linq.Expressions.Compiler.LambdaCompiler.Compile(LambdaExpression lambda)
   at System.Linq.Expressions.Expression`1.Compile(Boolean preferInterpretation)
   at HandlebarsDotNet.Compiler.FunctionBuilder.Compile(IEnumerable`1 expressions, String templatePath)
   at HandlebarsDotNet.Handlebars.HandlebarsEnvironment.Compile(String template)
   at HandlebarsTests.Tests.<RunPrecompiled>d__1.MoveNext() in D:\Repositories\git\HandlebarsTestRepo\HandlebarsTests\Tests.cs:line 25
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.RunWithDefaultContext()
   at Xunit.Sdk.AsyncTestSyncContext.<>c__DisplayClass7_0.<Post>b__1(Object _)
   at Xunit.Sdk.MaxConcurrencySyncContext.RunOnSyncContext(SendOrPostCallback callback, Object state)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at Xunit.Sdk.MaxConcurrencySyncContext.WorkerThreadProc()
   at Xunit.Sdk.XunitWorkerThread.<>c.<QueueUserWorkItem>b__5_0(Object _)
   at System.Threading.Tasks.Task.Execute()
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
   at System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
Unhandled Exception: 
Unhandled Exception:

**Comment by rexm** [comment] 2017-10-24 21:22
Have you tried reproducing this on some other environments?

**Comment by mikeprince3** [comment] 2017-10-24 21:24
I only tried Windows 10.

**Comment by EBMike** [comment] 2017-10-25 21:19
@rexm try clearing your nuget cache first. maybe you have a special version of handlebars in there

**Comment by rexm** [comment] 2017-10-29 17:17
After a little more work I was able to reproduce it. PR welcome.

**Comment by EBMike** [comment] 2017-10-30 15:23
@rexm Honestly, I was really hoping you guys might have an answer for this one... I looked into it a little bit, but I haven't really done any Linq Expression Builders before

**Comment by jeffogata** [comment] 2018-08-20 21:44
I used @EBMike's public repo and confirmed the test failure.  Updating to version 1.9.3 or above of Handlebars.Net allows the test to pass.

**Comment by rexm** [comment] 2019-04-27 20:14
No reports of this on newer versions, so closing for now.

**Closed by rexm** 2019-04-27 20:14 UTC
